baseurl = "/"
languageCode = "en-us"
title = "DB Browser for SQLite"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableEmoji = true
publishDir = "docs"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "Blog"
    url = "/blog/"
[[menu.main]]
    name = "Docs"
    url = "https://github.com/sqlitebrowser/sqlitebrowser/wiki"
[[menu.main]]
    name = "Download"
    url = "/dl/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/sqlitebrowser/sqlitebrowser"
[[menu.main]]
    name = "Slack"
    url = "https://db4s.slack.com"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/sqlitebrowser"

[params]
    description = "The Official home of the DB Browser for SQLite."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "sqlitebrowser.svg"
    width = 50
    height = 50
    alt = "DB Browser for SQLite logo"
